---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: leori/ci

inputs:
- name: ops-manager-cloudfoundry

run:
  path: ops-manager-cloudfoundry/ci/tasks/smoke-tests/run.sh
