---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: andreikrasnitski/ci

inputs:
- name: mongodb-on-demand-release

run:
  path: mongodb-on-demand-release/ci/tasks/smoke-tests/run.sh
