---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: leori/ci

inputs:
  - name: ops-manager-cloudfoundry
  - name: stemcell
  - name: version
  - name: artifacts

params:
  PCF_URL:
  PCF_USERNAME:
  PCF_PASSWORD:
  CONFIG:
  UPDATE_PAS:
  VERSION:

run:
  path: ops-manager-cloudfoundry/ci/tasks/deploy-tile/run.sh
