---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: leori/test

inputs:
- name: ops-manager-cloudfoundry
- name: stemcell
- name: version
- name: artifacts

params:
  PCF_URL:
  PCF_USERNAME:
  PCF_PASSWORD:
  PRODUCT_PROPERTIES:
  PRODUCT_NETWORK_AZS:
  OM_API_KEY:
  OM_API_USER:
  CONFIG:
  MONGO_VERSION:

run:
  path: ops-manager-cloudfoundry/ci/tasks/deploy-tile/run.sh
