---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: theburi/ci

inputs:
- name: ops-manager-cloudfoundry
- name: stemcell
- name: version
- name: artifacts

params:
  PCF_URL:
  PCF_USERNAME:
  PCF_PASSWORD:
  PRODUCT_PROPERTIES:
  PRODUCT_NETWORK_AZS:

run:
  path: ops-manager-cloudfoundry/ci/tasks/deploy-tile/run.sh
