---
name: mongodb
director_uuid: 510ac165-ee99-4c45-8274-1b989e5d5697

releases:
  - name: mongodb
    version: latest

stemcells:
  - alias: default
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

instance_groups:
  - name: mongod_node
    instances: 1
    jobs:
      - name: mongod_node
        release: mongodb
        consumes:
          mongod_node: {from: mongod_node}
        provides:
          mongod_node: {as: mongod_node}

    vm_type: default
    stemcell: default
    persistent_disk_type: default
    networks:
      - name: default

properties:
  mongo_ops:
    url: http://ec2-54-175-81-192.compute-1.amazonaws.com:8080
    api_key: 758e351b7a7612d049f6b415b90d4603
    group_id: 573f6377e4b00c8c02d5ecde
