---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: leori/ci

inputs:
  - name: ops-manager-cloudfoundry
  - name: artifacts
  - name: version

outputs:
  - name: release

run:
  path: ops-manager-cloudfoundry/ci/tasks/shipit/run.sh
