required = ["github.com/onsi/ginkgo/ginkgo"]

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.0"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/pivotal-cf-experimental/cf-test-helpers"

[prune]
  go-tests = true
  unused-packages = true
