---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: andreikrasnitski/ci

inputs:
- name: mongodb-on-demand-release
- name: on-demand-service-broker
- name: pcf-mongodb-helpers
- name: version

outputs:
- name: artifacts

run:
  path: mongodb-on-demand-release/ci/tasks/build-tile/run.sh
