---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: andreikrasnitski/ci

inputs:
- name: ops-manager-cloudfoundry
- name: bpm-release
- name: on-demand-service-broker-release
- name: syslog-migration-release
- name: pcf-mongodb-helpers
- name: version

outputs:
- name: artifacts

run:
  path: ops-manager-cloudfoundry/ci/tasks/build-tile/run.sh
