---
groups:
  - name: mongodb-on-demand
    jobs:
      - smoke-tests
  - name: versioning
    jobs:
      - patch
      - major
      - minor

resources:
- name: ops-manager-cloudfoundry
  type: git
  source:
    branch: dev
    uri: git@github.com:10gen/ops-manager-cloudfoundry.git
    private_key: ((git-private-key))

- name: version
  type: semver
  source:
    driver: s3
    bucket: ((aws-bucket))
    key: version
    region_name: eu-west-1
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))
    initial_version: ((initial-version))


jobs:
- name: smoke-tests
  serial: true
  build_logs_to_retain: 50
  plan:
  - aggregate:
    - get: ops-manager-cloudfoundry
      trigger: true
  - task: smoke-tests
    file: ops-manager-cloudfoundry/ci/tasks/smoke-tests/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))

- name: minor
  plan:
  - do:
    - get: version
      trigger: false
      params:
        bump: minor
    - put: version
      params:
        file: version/number

- name: patch
  plan:
  - do:
    - get: version
      trigger: false
      params:
        bump: patch
    - put: version
      params:
        file: version/number

- name: major
  plan:
  - do:
    - get: version
      trigger: false
      params:
        bump: major
    - put: version
      params:
        file: version/number
