---
resources:
- name: git
  type: git
  source:
    branch: ((git-branch))
    uri: ((git-uri))
- name: version
  type: semver
  source:
    driver: s3
    bucket: ((aws-bucket))
    key: version
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))
    initial_version: ((initial-version))
- name: stemcell
  type: s3
  source:
    bucket: ((aws-bucket))
    regexp: ((stemcell-regexp))
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))
- name: odb
  type: s3
  source:
    bucket: ((aws-bucket))
    regexp: ((odb-regexp))
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))
- name: tile
  type: s3
  source:
    bucket: ((aws-bucket))
    regexp: ((tile-regexp))
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))
- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-url))

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

jobs:
- name: run-tests
  serial: true
  plan:
  - get: git
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource: &golang-image
        type: docker-image
        source:
          repository: andreikrasnitski/golang-cf-cli
      inputs:
      - name: git
      run:
        path: ./git/ci/run-tests
        args: []
    on_failure: &slack-alert
      put: slack-alert
      params:
        channel:  ((slack-channel))
        username: ((slack-username))
        icon_url: ((slack-icon))
        text:     ((slack-failed-text))
- name: build-tile
  serial: true
  plan:
  - get: git
    trigger: true
    passed: [run-tests]
  - get: odb
    trigger: false
    params: {filename: on-demand-service-broker-0.16.0.tgz}
  - get: version
    trigger: false
  - task: build-tile
    config:
      platform: linux
      image_resource: &tile-pipeline-image
        type: docker-image
        source:
          repository: andreikrasnitski/tile-pipeline
      inputs:
      - name: git
      - name: odb
      - name: version
      outputs:
      - name: tile
      run:
        path: ./git/ci/build-tile
        args: []
    on_failure: *slack-alert
  - put: tile
    params:
      file: tile/mongodb-on-demand-*.pivotal
      acl: public-read
- name: deploy-tile
  serial: true
  plan:
  - get: git
    trigger: true
    passed: [build-tile]
  - get: tile
    trigger: false
    params: {filename: mongodb-on-demand-*.pivotal}
  - get: stemcell
    trigger: false
    params: {filename: bosh-stemcell-*.tgz}
  - get: version
    trigger: false
  - task: deploy-tile
    config:
      platform: linux
      image_resource: *tile-pipeline-image
      inputs:
      - name: git
      - name: stemcell
      - name: tile
      - name: version
      run:
        path: ./git/ci/deploy-tile
        args: []
      params:
        PCF_URL: ((pcf-url))
        PCF_USERNAME: ((pcf-username))
        PCF_PASSWORD: ((pcf-password))
        URL: ((mongo-url))
        USERNAME: ((mongo-username))
        API_KEY: ((mongo-apikey))
        VM_TYPE: ((mongo-vm))
        DISK_TYPE: ((mongo-disk))
        AZ: ((mongo-az))
    on_failure: *slack-alert
  - put: version
    params: {bump: patch}
- name: smoke-tests
  serial: true
  plan:
  - get: git
    trigger: true
    passed: [deploy-tile]
  - task: smoke-tests
    config:
      platform: linux
      image_resource: *golang-image
      inputs:
      - name: git
      run:
        path: ./git/ci/smoke-tests
        args: []
      params:
        CF_APPS_DOMAIN: ((cf-apps-domain))
        CF_SYSTEM_DOMAIN: ((cf-system-domain))
        CF_API: ((cf-api))
        CF_USER: ((cf-user))
        CF_PASSWORD: ((cf-password))
        SERVICE_NAME: ((service-name))
    on_failure: *slack-alert
