---
groups:
  - name: mongodb-on-demand
    jobs:
      - delete-tile
      - deploy-tile-old  
      - smoke-tests

resources:
- name: ops-manager-cloudfoundry
  type: git
  source:
    branch: tile-upgrade-playground
    uri: git@github.com:10gen/ops-manager-cloudfoundry.git
    private_key: ((git-private-key))

- name: stemcell
  type: pivnet
  source:
    api_token: ((pivnet-token))
    product_slug: stemcells-ubuntu-xenial
    product_version: '170.*'

- name: tileold
  type: pivnet
  source:
    api_token: ((pivnet-token))
    product_slug: mongodb-on-demand
    product_version: '1.1.0'

- name: version
  type: semver
  source:
    driver: s3
    bucket: ((aws-bucket))
    key: version
    region_name: eu-west-1
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))
    initial_version: 1.1.1

- name: versionold
  type: semver
  source:
    driver: s3
    bucket: ((aws-bucket))
    key: versionold
    region_name: eu-west-1
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))
    initial_version: 1.1.0

- name: artifacts
  type: s3
  source:
    bucket: ((aws-bucket))
    region_name: eu-west-1
    regexp: mongodb-on-demand-(.*).pivotal
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
- name: slack
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

jobs:
- name: deploy-tile-old
  serial: true
  build_logs_to_retain: 50
  plan:
  - in_parallel:
    - get: ops-manager-cloudfoundry
      passed: [ delete-tile ]
    - get: artifacts
      params:
        file: artifacts/mongodb-on-demand-*.pivotal
    - get: version
      trigger: true
    - get: versionold
    - get: stemcell
      params:
        globs: ["*google*"]
    - get: tileold
  - task: deploy-tile-old
    file: ops-manager-cloudfoundry/ci/tasks/deploy-tile-old/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))
      OM_API_USER: ((om-api-user))
      OM_API_KEY: ((om-api-key))
      PRODUCT_PROPERTIES: ((product_properties))
      PRODUCT_NETWORK_AZS: ((product_network_azs))
      CONFIG: config.pie22
  - task: deploy-mongodb-service
    file: ops-manager-cloudfoundry/ci/tasks/deploy-mongodb-service/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))

- name: smoke-tests
  serial: true
  build_logs_to_retain: 50
  plan:
  - in_parallel:
    - get: ops-manager-cloudfoundry
      trigger: true
      passed: [ deploy-tile-old ]
  - task: smoke-tests
    file: ops-manager-cloudfoundry/ci/tasks/smoke-tests/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))

- name: delete-tile
  serial: true
  build_logs_to_retain: 50
  plan:
  - in_parallel:
    - get: version
      trigger: true
    - get: ops-manager-cloudfoundry
  - task: delete-tile
    file: ops-manager-cloudfoundry/ci/tasks/delete-tile/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))