---
groups:
  - name: mongodb-on-demand
    jobs:
      - delete-tile
      - deploy-tile-old
      - deploy-mongodb-service
      - build-tile
      - update-tile-version
      - smoke-tests

resources:
- name: ops-manager-cloudfoundry
  type: git
  source:
    branch: tile-upgrade-playground
    uri: git@github.com:10gen/ops-manager-cloudfoundry.git
    private_key: ((git-private-key))

- name: stemcell
  type: pivnet
  source:
    api_token: ((pivnet-token))
    product_slug: stemcells-ubuntu-xenial
    product_version: '170.*'

- name: tileold
  type: pivnet
  source:
    api_token: ((pivnet-token))
    product_slug: mongodb-on-demand
    product_version: '1.1.0'

- name: version
  type: semver
  source:
    driver: s3
    bucket: ((aws-bucket))
    key: version
    region_name: eu-west-1
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))
    initial_version: 1.1.1

- name: versionold
  type: semver
  source:
    driver: s3
    bucket: ((aws-bucket))
    key: versionold
    region_name: eu-west-1
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))
    initial_version: 1.1.0

- name: artifacts
  type: s3
  source:
    bucket: ((aws-bucket))
    region_name: eu-west-1
    regexp: mongodb-on-demand-(.*).pivotal
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
- name: slack
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

jobs:
- name: deploy-tile-old
  serial: true
  build_logs_to_retain: 50
  plan:
  - in_parallel:
    - get: ops-manager-cloudfoundry
      trigger: true
      passed: [ delete-tile ]
    - get: artifacts
      params:
        file: artifacts/mongodb-on-demand-*.pivotal
    - get: version
    - get: versionold
    - get: stemcell
      params:
        globs: [((globs-param))]
    - get: tileold
  - task: deploy-tile-old
    file: ops-manager-cloudfoundry/ci/tasks/deploy-tile-old/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))
      OM_API_USER: ((om-api-user))
      OM_API_KEY: ((om-api-key))
      PRODUCT_PROPERTIES: ((product_properties))
      PRODUCT_NETWORK_AZS: ((product_network_azs))
      CONFIG: ((env-config))

- name: build-tile
  serial: true
  build_logs_to_retain: 50
  plan:
  - in_parallel:
    - get: ops-manager-cloudfoundry
      trigger: true
    - get: on-demand-service-broker-release
      params:
        filename: on-demand-service-broker-(.*).tgz
    - get: syslog-migration-release
      params:
        filename: syslog-migration-(.*).tgz
    - get: pcf-mongodb-helpers
      params:
        filename: pcf-mongodb-helpers-(.*).tgz
    - get: bpm-release
      params:
        filename: bpm-release-(.*).tgz
    - get: mongodb
      params:
        filename: mongodb-linux-x86_64-ubuntu1604-(.*).tgz
    - get: version
      params:
        pre: rc
  - put: "build-status"
    params:
      state: "pending"
      commit: "ops-manager-cloudfoundry"
  - task: build-tile
    file: ops-manager-cloudfoundry/ci/tasks/build-tile/task.yml
    on_failure:
      put: "build-status"
      params:
        state: "failure"
        commit: "ops-manager-cloudfoundry"
    on_error:
      put: "build-status"
      params:
        state: "error"
        commit: "ops-manager-cloudfoundry"
    on_abort:
      put: "build-status"
      params:
        state: "error"
        commit: "ops-manager-cloudfoundry"
        description: aborted
      params:
        AWS_KEY: ((aws-access-key))
        AWS_SECRET_KEY: ((aws-secret-access-key))
  - put: artifacts
    params:
      file: artifacts/mongodb-on-demand-*.pivotal
  - put: version
    params:
      pre: rc
  - put: "build-status"
    params:
      state: "success"
      commit: "ops-manager-cloudfoundry"

- name: update-tile-version
  serial: true
  build_logs_to_retain: 50
  plan:
  - in_parallel:
    - get: ops-manager-cloudfoundry
      trigger: false
      passed: [ deploy-mongodb-service ]
    - get: artifacts
      params:
        file: artifacts/mongodb-on-demand-*.pivotal
    - get: version
    - get: stemcell
      params:
        globs: [((globs-param))]
  - task: use application
    file: ops-manager-cloudfoundry/ci/tasks/application-check/task-put.yml
  - task: deploy-tile
    file: ops-manager-cloudfoundry/ci/tasks/deploy-tile/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))
      OM_API_KEY: ((om-api-key))
      OM_API_USER: ((om-api-user))
      PRODUCT_PROPERTIES: ((product_properties))
      PRODUCT_NETWORK_AZS: ((product_network_azs))
      CONFIG: ((env-config))
  - task: check application
    file: ops-manager-cloudfoundry/ci/tasks/application-check/task-get.yml

- name: deploy-mongodb-service
  serial: true
  build_logs_to_retain: 50
  plan:
    - in_parallel:
        - get: ops-manager-cloudfoundry
          trigger: true
          passed: [ deploy-tile-old ]
    - task: deploy-mongodb-service
      file: ops-manager-cloudfoundry/ci/tasks/deploy-mongodb-service/task.yml
      params:
        CF_APP_URL: ((cf-app-url))
        CF_APP_USER: ((cf-app-username))
        CF_APP_PASSWORD: ((cf-app-password))
        REPLICA_SET_PLAN: replica_set_small
        BACKUP_ENABLED: true

- name: smoke-tests
  serial: true
  build_logs_to_retain: 50
  plan:
  - in_parallel:
    - get: ops-manager-cloudfoundry
      trigger: true
      passed: [ update-tile-version ]
  - task: smoke-tests
    file: ops-manager-cloudfoundry/ci/tasks/smoke-tests/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))

- name: delete-tile
  serial: true
  build_logs_to_retain: 50
  plan:
  - in_parallel:
    - get: version
    - get: ops-manager-cloudfoundry
      trigger: true
  - task: delete-tile
    file: ops-manager-cloudfoundry/ci/tasks/delete-tile/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))
