---
groups:
  - name: mongodb-on-demand
    jobs:
      - build-tile
      - deploy-tile-old
      - deploy-tile
      - delete-tile
      - smoke-tests

resources:
- name: ops-manager-cloudfoundry
  type: git
  source:
    branch: feature/CFTILE-35
    uri: git@github.com:10gen/ops-manager-cloudfoundry.git
    private_key: ((git-private-key))

- name: stemcell
  type: pivnet
  source:
    api_token: ((pivnet-token))
    product_slug: stemcells-ubuntu-xenial
    product_version: '170.*'

- name: version
  type: semver
  source:
    driver: s3
    bucket: ((aws-bucket))
    key: version
    region_name: eu-west-1
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))
    initial_version: 1.0.34

- name: on-demand-service-broker-release
  type: s3
  source:
    bucket: ((aws-bucket))
    region_name: eu-west-1
    regexp: on-demand-service-broker-(.*).tgz
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))

- name: mongodb
  type: s3
  source:
    bucket: ((aws-bucket))
    region_name: eu-west-1
    regexp: mongodb-linux-x86_64-ubuntu1604-(.*).tgz

    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))

- name: pcf-mongodb-helpers
  type: s3
  source:
    bucket: ((aws-bucket))
    region_name: eu-west-1
    regexp: pcf-mongodb-helpers-(.*).tgz
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))

- name: syslog-migration-release
  type: s3
  source:
    bucket: ((aws-bucket))
    region_name: eu-west-1
    regexp: syslog-migration-(.*).tgz
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))

- name: bpm-release
  type: s3
  source:
    bucket: ((aws-bucket))
    region_name: eu-west-1
    regexp: bpm-release-(.*).tgz
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))

- name: artifacts
  type: s3
  source:
    bucket: ((aws-bucket))
    region_name: eu-west-1
    regexp: mongodb-on-demand-(.*).pivotal
    access_key_id: ((aws-access-key))
    secret_access_key: ((aws-secret-access-key))
- name: tileold
  type: pivnet
  source:
    api_token: ((pivnet-token))
    product_slug: mongodb-on-demand
    product_version: '1.1.1'

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
- name: slack
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

jobs:
- name: build-tile
  serial: true
  build_logs_to_retain: 50
  plan:
  - in_parallel:
    - get: ops-manager-cloudfoundry
      trigger: true
      passed: [ delete-tile ]
    - get: on-demand-service-broker-release
      params:
        filename: on-demand-service-broker-(.*).tgz
    - get: syslog-migration-release
      params:
        filename: syslog-migration-(.*).tgz
    - get: pcf-mongodb-helpers
      params:
        filename: pcf-mongodb-helpers-(.*).tgz
    - get: bpm-release
      params:
        filename: bpm-release-(.*).tgz
    - get: mongodb
      params:
        filename: mongodb-linux-x86_64-ubuntu1604-(.*).tgz
    - get: version
      params:
        pre: rc
  - task: build-tile
    file: ops-manager-cloudfoundry/ci/tasks/build-tile/task.yml
    params:
      AWS_KEY: ((aws-access-key))
      AWS_SECRET_KEY: ((aws-secret-access-key))
  - put: artifacts
    params:
      file: artifacts/mongodb-on-demand-*.pivotal
  - put: version
    params:
      pre: rc


- name: deploy-tile-old
  serial: true
  build_logs_to_retain: 50
  plan:
  - in_parallel:
    - get: ops-manager-cloudfoundry
      trigger: true
      passed: [ build-tile ]
    - get: artifacts
      params:
        file: artifacts/mongodb-on-demand-1.1.1.pivotal
    - get: stemcell
      params:
        globs: ["*google*"]
    - get: tileold
  - task: deploy-tile-old
    file: ops-manager-cloudfoundry/ci/tasks/deploy-tile-old/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))
      OM_API_USER: ((om-api-user))
      OM_API_KEY: ((om-api-key))
      PRODUCT_PROPERTIES: ((product_properties))
      PRODUCT_NETWORK_AZS: ((product_network_azs))
      CONFIG: config.pie22

- name: deploy-tile
  serial: true
  build_logs_to_retain: 50
  plan:
  - aggregate:
    - get: ops-manager-cloudfoundry
      trigger: true
      passed: [ deploy-tile-old ]
    - get: artifacts
      params:
        file: artifacts/mongodb-on-demand-*.pivotal
    - get: version
    - get: stemcell
      params:
        globs: ["*google*"]
  - task: deploy-tile
    file: ops-manager-cloudfoundry/ci/tasks/deploy-tile/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))
      OM_API_USER: ((om-api-user))
      OM_API_KEY: ((om-api-key))
      PRODUCT_PROPERTIES: ((product_properties))
      PRODUCT_NETWORK_AZS: ((product_network_azs))
      CONFIG: config.pie22

- name: smoke-tests
  serial: true
  build_logs_to_retain: 50
  plan:
  - in_parallel:
    - get: ops-manager-cloudfoundry
      trigger: true
      passed: [ deploy-tile ]
  - task: smoke-tests
    file: ops-manager-cloudfoundry/ci/tasks/smoke-tests/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))

- name: delete-tile
  serial: true
  build_logs_to_retain: 50
  plan:
  - aggregate:
    - get: ops-manager-cloudfoundry
      trigger: true
  - task: delete-tile
    file: ops-manager-cloudfoundry/ci/tasks/delete-tile/task.yml
    params:
      PCF_URL: ((pcf-url))
      PCF_USERNAME: ((pcf-username))
      PCF_PASSWORD: ((pcf-password))

