---
groups:
  - name: mongodb-on-demand
    jobs:
      - deploy-tile
      - smoke-tests

resources:
  - name: ops-manager-cloudfoundry
    type: git
    source:
      branch: ((git-branch-name))
      uri: git@github.com:10gen/ops-manager-cloudfoundry.git
      private_key: ((git-private-key))

  - name: stemcell
    type: pivnet
    source:
      api_token: ((pivnet-token))
      product_slug: stemcells-ubuntu-xenial
      product_version: 170.*

  - name: version
    type: semver
    source:
      driver: s3
      bucket: ((aws-bucket))
      key: version
      region_name: eu-west-1
      access_key_id: ((aws-access-key))
      secret_access_key: ((aws-secret-access-key))
      initial_version: 1.2.0

  - name: artifacts
    type: s3
    source:
      bucket: ((aws-bucket))
      region_name: eu-west-1
      regexp: mongodb-on-demand-(1.*).pivotal
      access_key_id: ((aws-access-key))
      secret_access_key: ((aws-secret-access-key))

  - name: "deploy-status"
    type: "github-status"
    source:
      repository: 10gen/ops-manager-cloudfoundry
      access_token: ((repo-github-token))
      context: deploy-tile

  - name: "test-status"
    type: "github-status"
    source:
      repository: 10gen/ops-manager-cloudfoundry
      access_token: ((repo-github-token))
      context: smoke-tests

resource_types:
  - name: pivnet
    type: docker-image
    source:
      repository: pivotalcf/pivnet-resource
      tag: latest-final
  - name: slack
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
  - name: "github-status"
    type: "docker-image"
    source:
      repository: "dpb587/github-status-resource"
      tag: "master"

jobs:
  - name: deploy-tile
    serial: true
    serial_groups: [same-deployment]
    build_logs_to_retain: 5
    plan:
      - get: ops-manager-cloudfoundry
        trigger: true
      - in_parallel:
          - get: artifacts
            params:
              file: artifacts/mongodb-on-demand-*.pivotal
          - get: version
          - get: stemcell
            params:
              globs: [((globs-param))]
          - put: "deploy-status"
            params:
              state: "pending"
              commit: "ops-manager-cloudfoundry"
      - task: deploy-tile
        file: ops-manager-cloudfoundry/ci/tasks/deploy-tile/task.yml
        params:
          PCF_URL: ((pcf-url))
          PCF_USERNAME: ((pcf-username))
          PCF_PASSWORD: ((pcf-password))
          CONFIG: ((env-config))
        on_failure:
          put: "deploy-status"
          params:
            state: "failure"
            commit: "ops-manager-cloudfoundry"
        on_error:
          put: "deploy-status"
          params:
            state: "error"
            commit: "ops-manager-cloudfoundry"
        on_abort:
          put: "deploy-status"
          params:
            state: "error"
            commit: "ops-manager-cloudfoundry"
            description: aborted
      - put: "deploy-status"
        params:
          state: "success"
          commit: "ops-manager-cloudfoundry"

  - name: smoke-tests
    serial: true
    serial_groups: [same-deployment]
    build_logs_to_retain: 50
    plan:
      - get: ops-manager-cloudfoundry
        trigger: false
      - put: "test-status"
        params:
          state: "pending"
          commit: "ops-manager-cloudfoundry"
      - in_parallel:
          - task: standalone_small
            file: ops-manager-cloudfoundry/ci/tasks/smoke-tests/task.yml
            params:
              PCF_URL: ((pcf-url))
              PCF_USERNAME: ((pcf-username))
              PCF_PASSWORD: ((pcf-password))
              PLAN_NAMES: '["standalone_small"]'
              BACKUP_ENABLED: '["false"]'
              SSL_ENABLED: '["false"]'
              MONGO_VERSION: '[]'
              CONFIG: ((env-config))
          - task: replica_set_small
            file: ops-manager-cloudfoundry/ci/tasks/smoke-tests/task.yml
            params:
              PCF_URL: ((pcf-url))
              PCF_USERNAME: ((pcf-username))
              PCF_PASSWORD: ((pcf-password))
              PLAN_NAMES: '["replica_set_small"]'
              BACKUP_ENABLED: '["false"]'
              SSL_ENABLED: '["false"]'
              MONGO_VERSION: '[]'
              CONFIG: ((env-config))
          - task: sharded_cluster_small
            file: ops-manager-cloudfoundry/ci/tasks/smoke-tests/task.yml
            params:
              PCF_URL: ((pcf-url))
              PCF_USERNAME: ((pcf-username))
              PCF_PASSWORD: ((pcf-password))
              PLAN_NAMES: '["sharded_cluster_small"]'
              BACKUP_ENABLED: '["false"]'
              SSL_ENABLED: '["false"]'
              MONGO_VERSION: '[]'
              CONFIG: ((env-config))
        on_failure:
          put: "test-status"
          params:
            state: "failure"
            commit: "ops-manager-cloudfoundry"
        on_error:
          put: "test-status"
          params:
            state: "error"
            commit: "ops-manager-cloudfoundry"
        on_abort:
          put: "test-status"
          params:
            state: "error"
            commit: "ops-manager-cloudfoundry"
            description: aborted
      - put: "test-status"
        params:
          state: "success"
          commit: "ops-manager-cloudfoundry"
