---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: andreikrasnitski/ci

inputs:
- name: mongodb-on-demand-release

params:
  PCF_URL:
  PCF_USERNAME:
  PCF_PASSWORD:

run:
  path: mongodb-on-demand-release/ci/tasks/delete-tile/run.sh
