---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: leori/test

inputs:
- name: ops-manager-cloudfoundry

params:
  PCF_URL:
  PCF_USERNAME:
  PCF_PASSWORD:

run:
  path: ops-manager-cloudfoundry/ci/tasks/application-check/run-get.sh