---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: leori/ci

inputs:
  - name: ops-manager-cloudfoundry
  - name: stemcell
  - name: tileold

params:
  PCF_URL:
  PCF_USERNAME:
  PCF_PASSWORD:
  CONFIG:

run:
  path: ops-manager-cloudfoundry/ci/tasks/deploy-tile-old/run.sh
